name: Mysa
favicon: null
layout_spectrum: 1
typography_spectrum: 0.34807
title: Mysa Marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8da9b1'
    - '#010100'
    - '#fefff6'
    - '#fe7218'
    - '#962b07'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
